accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

    path('register/',views.register,name='register'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    path('reset_password/',views.reset_password,name='reset_password'),
    
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [

    path('',views.home,name='home'),
    path('<str:category_slug>/',views.home,name='category_slug'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('home/',include('home.urls',namespace='home')),
    path('team/',include('team.urls',namespace='team')),
    path('about/',include('about.urls',namespace='about')),
    path('testimonials/',include('testimonials.urls',namespace='testimonials')),
    path('service/',include('service.urls',namespace='service')),
    path('menu/',include('menu.urls',namespace='menu')),
    path('booking/',include('booking.urls',namespace='booking')),
    path('contact/',include('contact.urls',namespace='contact')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid
# Create your models here.


def uplad_user_image(instance , file_name):
    extension = file_name.split('.')[1]
    return f'user/{instance.user}.{extension}'



class Account(models.Model):
    id = models.UUIDField(primary_key = True , default = uuid.uuid4 , editable = False)
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    image = models.ImageField(upload_to=uplad_user_image, height_field=None, width_field=None, max_length=None , null=True, blank=True)
    phone = models.CharField(max_length=50)


    class Meta:
        verbose_name = ("Account")
        verbose_name_plural = ("Accounts")

    def __str__(self):
        return str(self.user)
    
    @receiver(post_save , sender=User)
    def create_user_account(sender , instance , created , **kwargs):
        if created:
            Account.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Account

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email']

class LoginForm(forms.Form):
    username = forms.CharField(
        label='Username',
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
    )

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Account
        fields  = '__all__'        
        exclude = 'user',



class ResetPasswordForm(forms.Form):
    username = forms.CharField(
        label='Username',
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
    )
    confirm_password = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'})
    )

accounts/views.py
from django.shortcuts import render , redirect
from . models import Account , User
from django.contrib.auth import authenticate,login,logout
from . forms import LoginForm , RegisterForm , ProfileForm , UserForm 
from django.http import HttpResponse


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST , request.FILES)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username = username, password = password)
            login(request , user)
            return redirect('accounts:profile')
        else:
            return HttpResponse('Please Enter At Least All Data Without Image')
    else:
        form = RegisterForm()

    return render(request, 'accounts/register.html' , {'form': form,})



def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username = username , password = password)
            login(request , user)
            return redirect('accounts:profile')
        else:
            return HttpResponse('Please Enter Your Username And Password')
    else:
        form = LoginForm()

    return render(request , 'accounts/login.html' , {'form': form,})



def logout_view(request):
    logout(request)
    return redirect('accounts:login')


def profile(request):
    return render(request , 'accounts/profile.html')



def edit_profile(request):
    account = Account.objects.get(user=request.user)
    if request.method == "POST":
        u = UserForm(request.POST,request.FILES,instance=request.user)
        p = ProfileForm(request.POST,request.FILES,instance=account)
        if u.is_valid() and p.is_valid():
            u.save()
            p.save()
            return redirect('accounts:profile')
    else:

        u = UserForm(instance=request.user)
        p = ProfileForm(instance=account)

    context = {
        'userForm':u,
        'profileForm' :p,
    }
    return render(request,'accounts/edit_profile.html',context)



def reset_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password1']
        confirm_password = request.POST['password2']
        if confirm_password == password:
            user_exists = User.objects.filter(email = email).exists()
            if user_exists:
                user = User.objects.get(email = email)
                user.set_password(password)
                user.save()
                return redirect('accounts:profile')
        else:
            return HttpResponse('Please Enter Password Equal To Reset Password')
        
    return render(request , 'accounts/reset_password.html')

templates/accounts/edit_profile.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<div class="col-lg-7 mb-5 mx-auto">
    <div class="contact-form bg-light p-30">
        <div class="registration form">
            <h1 class="mb-4">Edit Profile</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form userForm %}
                {% bootstrap_form profileForm %}
                <button type='submit' class="btn btn-primary">Submit</button>
            </form>
            <div class="signup">
            <span class="signup">Already have an account?
            <a href="{% url "accounts:login" %}">Login</a>
            </span>
            </div>
        </div>
    </div>
</div>        


{% endblock content %}

templates/accounts/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<div class="col-lg-7 mb-5 mx-auto">
    <div class="contact-form bg-light p-30">
        <div class="login form">
            <h1>Login</h1>
            <form method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                <a href="{% url "accounts:reset_password" %}">Forgot password?</a>
                <button type='submit' class="btn btn-primary">Login</button>
            </form>
            <div class="signup">
            <span class="signup">Don't have an account?
                <a href="{% url "accounts:register" %}">Signup</a>
            </span>
            </div>
        </div>
    </div>
</div>        
{% endblock content %}

templates/accounts/profile.html
{% extends "base.html" %}
{% block content %}
<div class="col-lg-7 mb-5 mx-auto">
    <div class="contact-form bg-light p-30">
        <div class="login form">
            <h1>Profile</h1> <br>
                {% if profile.image %}
                    <img src="{{profile.image.url}}" alt="" style="width: 50px;height: 50px;border-radius: 40%;"> <br>
                {% endif %}
                <br>
                <label for=""> {{profile.user.username}} </label> <br>
                <label for=""> {{profile.user.first_name}} </label><br>
                <label for=""> {{profile.user.last_name}} </label><br>
                <label for=""> {{profile.user.email}} </label><br>
                <label for=""> {{profile.phone}} </label><br>
                
                <a href="{% url "accounts:edit_profile" %}" class="btn btn-primary">Edit</a>
        </div>
    </div>
</div>    
{% endblock content %}

templates/accounts/register.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<div class="col-lg-7 mb-5 mx-auto">
    <div class="contact-form bg-light p-30">
        <div class="registration form">
            <h1>Signup</h1>
            <form method="POST" enctype = "multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type='submit' class="btn btn-primary">Register</button>
            </form>
            <div class="signup">
            <span class="signup">Already have an account?
            <a href="{% url "accounts:login" %}">Login</a>
            </span>
            </div>
        </div>
    </div>
</div>        
{% endblock content %}

templates/accounts/reset_password.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-7 mb-5">
            <div class="contact-form bg-light p-3 p-lg-5">
                <div class="login form">
                    <h1 class="mb-4">Reset Password</h1>
                    <form method="POST" class="needs-validation" novalidate>
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="email" class="form-control" id="email" placeholder="Enter your Email" name="email" required>
                            <div class="invalid-feedback">
                                Please provide a valid email.
                            </div>
                        </div>
                        <div class="mb-3">
                            <input type="password" class="form-control" id="password1" placeholder="Enter New password" name="password1" required>
                            <div class="invalid-feedback">
                                Please provide a valid password.
                            </div>
                        </div>
                        <div class="mb-3">
                            <input type="password" class="form-control" id="password2" placeholder="Confirm New password" name="password2" required>
                            <div class="invalid-feedback">
                                Please confirm your password.
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Reset Password</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}