home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [

    path('',views.home,name='home'),
    path('<str:category_slug>/',views.home,name='category_slug'),
    
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [

    path('',views.menu,name='menu'),
    path('<str:category_slug>/',views.menu,name='category_slug'),

]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('home/',include('home.urls',namespace='home')),
    path('team/',include('team.urls',namespace='team')),
    path('about/',include('about.urls',namespace='about')),
    path('testimonials/',include('testimonials.urls',namespace='testimonials')),
    path('service/',include('service.urls',namespace='service')),
    path('menu/',include('menu.urls',namespace='menu')),
    path('booking/',include('booking.urls',namespace='booking')),
    path('contact/',include('contact.urls',namespace='contact')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/models.py
from django.db import models

# Create your models here.

menu/views.py
from django.shortcuts import render
from product.models import Product
from category.models import Category
from django.contrib.auth.decorators import login_required
# Create your views here.




@login_required(login_url='accounts:login')
def menu(request , category_slug = None):
    categories = Category.objects.all()
    if category_slug != None:
        category = Category.objects.get(slug=category_slug)
        products = Product.objects.filter(category = category , is_active=True)
    else:
        products = Product.objects.all()
        
    context = {
        'products':products,
        'categories':categories,
    }
    return render(request , 'menu/menu.html' , context)

templates/menu/menu.html
{% extends "base.html" %}
{% block content %}

        <!-- Menu Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h5 class="section-title ff-secondary text-center text-primary fw-normal">Food Menu</h5>
                    <h1 class="mb-5">Most Popular Items</h1>
                </div>
                <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.1s">
                    <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
                        {% for category in categories %}
                        <li class="nav-item">
                            <a class="d-flex align-items-center text-start mx-3 pb-3" data-bs-toggle="pill">
                                <div class="ps-3">
                                    <a href="{% url "menu:category_slug" category.slug %}" class="d-flex align-items-center text-start mx-3 pb-3">{{category}}</a>
                                </div>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane fade show p-0 active">
                            <div class="row g-4">
                                {% for product in products %}
                                <div class="col-lg-6">
                                    <div class="d-flex align-items-center">
                                        <img class="flex-shrink-0 img-fluid rounded" src="{{product.image.url}}" alt="" style="width:80px;height:80px;">
                                        <div class="w-100 d-flex flex-column text-start ps-4">
                                            <h5 class="d-flex justify-content-between border-bottom pb-2">
                                                <span>{{product}}</span>
                                                <span class="text-primary">${{product.price}}</span>
                                            </h5>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Menu End -->

{% endblock content %}